# Exective summary of Work Package 2

## Objectives

This work package aims at developing a data-driven fault detection algorithm for the motors in the robot. The algorithm should be able to accurately detect faults under different working conditions of the robot, and to display the results in the GUI developed in WP1.

## Tasks

- Task 1: Training data generation: Generate training data for your model, considering different working conditions of the robot.
- Task 2: Model development.
  - Data cleaning, preprocessing
  - Investigate different possible model and train the final model
- Task 3: GUI design and implementation.
- Task 4: Data challenge: Each group will generate a separate dataset, which will be used to construct a final evaluation dataset for the other groups. The performance of your model will be evaluated through this testing dataset.

## Delierables

- A Jupyter notebook reporting the model development process, including but not limited to:
  - Data cleaning, preprocessing
  - The models you tried and their performance evaluation through cross validation
  - The final model with best performance
- A demo software for condition-monitoring and fault detection:
  - The software should be able to read the data from the robot and display the results in the GUI.
  - The software should be able to detect faults in the robot and display the results in the GUI.
  - Record a video with the robot to demonstrate the functionality of your software.


# Working plan for today's TD

Today, we mainly work on task 2. More specifically, we will work on the following:
1. Explore the data we collected last week, including:
    - Data visualization to explore the patterns of the data
    - Use Principle Component Analysis (PCA) or t-SNE to visualize the data, in order to have a first flavor about the difficulty of the problem 
    - Explore if we have a significant difference between different sequences through visualization and clustering
2. Data cleaning and preprocessing
    - Missing values and outlier handling
    - Feature engineering
3. Apply statistical testing approach.
4. Apply a simple logistic regression model as a benchmark model for the classification task.

Before starting, please:
- Fetch the most up-to-date version of the github repository.
- Create a new branch called "WP2_TD_Lect_6_YourName", based on the branch "zhiguo_dev_DARR" and switch to it.
- Copy the notebook WP2_DATA-DRIVEN FAULT DETECTION/support/WP2_TD_Lect_6 to WP2_DATA-DRIVEN FAULT DETECTION/TD_6/, and rename it to TD_Lect_6_YourName.ipynb
- After finishing this task, push your changes to your github repository.
- Submit a pull request to the "zhiguo_dev" branch.

# Exercise 5 Implement logistic regression

Logistic regression is a simple and powerful machine learning algorithm. It is used for classification problems. It is a binary classifier, meaning that it can distinguish between only two classes. Often, it is used as a "quick and dirty" method to create benchmark for a classification problem.

In this exercise, we will implement logistic regression in our dataset. You will try:
- Use sklearn to implement logistic regression
- Hyper-parameter tuning in logistic regression
- Use cross-validation to evaluate the performance of your model



### Task 1: Effect of hyper-parameter and normalization

Below is a sample code for logistic regression.
- Try to change different values of hyper-parameter $C$, and see the impact on the results.
- In this code, we did not do any preprocessing on the data. You can try to implement your preprocessing and see the impacts on the results.

In [21]:
import warnings

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score
from utility import read_data


warnings.filterwarnings('ignore')

path_normal = r'C:\Users\MEDION\Documents\GitHub\digital_twin_robot\course_project_DARR\WP2_Data-driven fault detection\Data collection_20231109\Normal sequence'
path_failure = r'C:\Users\MEDION\Documents\GitHub\digital_twin_robot\course_project_DARR\WP2_Data-driven fault detection\Data collection_20231109\Failure sequence'
df = read_data(path_normal, path_failure)
 
print(df.columns)
 
# Separate the features (X) and the target variable (y)
X = df.drop(['label', 'sequence_idx', 'time'], axis=1)
y = df['label']
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a logistic regression model
logreg = LogisticRegression(C=.1)
logreg.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = logreg.predict(X_test)

# Compute and print the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Calculate precision
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

# Calculate recall
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

Index(['time', 'data_motor_1_position', 'data_motor_1_temperature',
       'data_motor_1_voltage', 'data_motor_2_position',
       'data_motor_2_temperature', 'data_motor_2_voltage',
       'data_motor_3_position', 'data_motor_3_temperature',
       'data_motor_3_voltage', 'data_motor_4_position',
       'data_motor_4_temperature', 'data_motor_4_voltage',
       'data_motor_5_position', 'data_motor_5_temperature',
       'data_motor_5_voltage', 'data_motor_6_position',
       'data_motor_6_temperature', 'data_motor_6_voltage', 'sequence_idx',
       'label'],
      dtype='object')
[[348  53]
 [ 36 282]]
Accuracy: 0.8762169680111266
Precision: 0.8417910447761194
Recall: 0.8867924528301887


## Task 2: Use $k$-fold cross validation to evaulate the performance

In the previous sample code, we used a single train-test split to evaluate the performance of our model. However, in practice, we want to use a more robust method to evaluate the performance of our model. One common method is to use $k$-fold cross validation. In this task, we will use $k$-fold cross validation to evaluate the performance of our model. Please implement a cross-validation with $k=5$, and calculate the average accuracy, precision, recall and F1 score of the tests.

This is a routine task which can be easily sovled by current LLM like chatgpt or Tongyi Lingma. I let you try to generate your code by yourself.



In [22]:
import warnings
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, KFold

warnings.filterwarnings('ignore')
# Creating a Logistic Regression model
log_reg = LogisticRegression(max_iter=5000)

# Performing 5-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(log_reg, X, y, cv=kfold, scoring='accuracy')

# Printing the accuracy scores for each fold
print("Accuracy scores for each fold:", cv_scores)

# Calculating and printing the mean accuracy
mean_accuracy = cv_scores.mean()
print("Mean Accuracy:", mean_accuracy)


Accuracy scores for each fold: [0.93741307 0.92489569 0.93602225 0.93184979 0.94853964]
Mean Accuracy: 0.9357440890125173


## Task 3: Tuning the hyper-parameter of the model

We can tune the hyper-parameters of our model by using the GridSearchCV function. A more efficient way is to create a pipeline that includes the hyper-parameter tuning, and prediction. You can try to generate the code using the following prompt:

```Prompt
Create a pipeline, where the first step is to use GridSearchcv to tune the hyper-parameter C of a logistic regression, and the second step is to use the best parameters to make predictions. 

Try to implement the generated code on our dataset here:

In [23]:
import warnings
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

warnings.filterwarnings('ignore')

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creating a pipeline with GridSearchCV
pipeline = Pipeline([('log_reg', LogisticRegression())])

# Parameter grid for GridSearchCV
param_grid = {'log_reg__C': np.logspace(-5, 10, num=100) } # Adjust the values as needed

# GridSearchCV to find the best parameters
grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Getting the best parameters and best estimator
best_params = grid_search.best_params_
best_estimator = grid_search.best_estimator_

print("Best Parameters:", best_params)

# Using the best estimator to make predictions
y_pred = best_estimator.predict(X_test)

# Evaluating the model (e.g., accuracy)
accuracy = best_estimator.score(X_test, y_test)
print("Accuracy:", accuracy)

Best Parameters: {'log_reg__C': 0.030538555088334154}
Accuracy: 0.7552155771905424


In [24]:
from sklearn.model_selection import GridSearchCV
import numpy as np

# Define the parameter grid for C
param_grid = {'C': np.logspace(-4, 1, 20)}

# Create and fit the GridSearchCV
grid_search = GridSearchCV(logreg, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Make predictions using the best model found by GridSearchCV
y_pred = grid_search.predict(X_test)

## Task 4: Use the pipeline in cross validation

Then, you can use your defined pipeline to automatically tune the hyper-parameter and use the best model for classification. Please try this on the code of Task 2, i.e., use the pipeline in the cross validation. You just need to replace the logistic classifier with the pipeline.

In [25]:
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
import numpy as np

kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    grid_search = GridSearchCV(logreg, param_grid, cv=5)
    grid_search.fit(X_train, y_train)

    y_pred = grid_search.predict(X_test)

    # Evaluation metrics
    conf_matrix = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)

    print(f"Confusion Matrix:\n{conf_matrix}\n")
    print(f"Accuracy: {accuracy}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")

Confusion Matrix:
[[336  65]
 [ 77 241]]

Accuracy: 0.8025034770514604
Precision: 0.7875816993464052
Recall: 0.7578616352201258
Confusion Matrix:
[[325  59]
 [ 92 243]]

Accuracy: 0.7899860917941586
Precision: 0.804635761589404
Recall: 0.7253731343283583
Confusion Matrix:
[[333  33]
 [ 44 309]]

Accuracy: 0.8929068150208623
Precision: 0.9035087719298246
Recall: 0.8753541076487252
Confusion Matrix:
[[320  51]
 [119 229]]

Accuracy: 0.7635605006954103
Precision: 0.8178571428571428
Recall: 0.6580459770114943
Confusion Matrix:
[[330  45]
 [ 71 273]]

Accuracy: 0.8386648122392212
Precision: 0.8584905660377359
Recall: 0.7936046511627907
